% This is a code containing all of the acoustic parameters necessary for
% the agar-acrylic simulations.
%
% Each medium must contain the following parameters:
%
%   - Longitudinal Velocity (m/s)
%   - Shear Velocity (m/s)
%   - Density (kg/m^3)
%   - Longitudinal Attenuation Coefficient (Nep/m/MHz)
%   - Shear Attenuation Coefficient (Nep/m/MHz)
%   - Thermal Conductivity (W/m/K)
%   - Specific Heat Capacity (J/kg/K)
%   - Perfusion Rate (s^-1)

function parameters = Parameters()

    parameters = struct;
    
    parameters.blood = struct(          'c_l', 0,           ... 
                                        'c_s', 0,           ...
                                        'rho', 1060,        ...
                                        'alpha_l', 0,       ...
                                        'alpha_s', 0,       ...
                                        'kt', 0,            ...    
                                        'ct', 3.84e3,       ...
                                        'wt', 0 );
                                
    parameters.bone = struct(           'c_l', 2850,        ... % Duck 1990, pg 82
                                        'c_s', 0,           ... 
                                        'rho', 1900,        ...
                                        'alpha_l', 97,      ...
                                        'alpha_s', 105,     ...
                                        'kt', 0.6,          ...
                                        'ct', 1.3e3,        ...
                                        'wt', 0 );
                        
    parameters.bone.c_s = (1400/2550)*parameters.bone.c_l;      % Jones, O'Reilly, Hynynen 2013
    parameters.bone.wt = 0.14 * (parameters.bone.rho * 1e-6 * 1e3 / 60);
    
    parameters.cartilage = struct(      'c_l', 1640,        ...
                                        'c_s', 0,           ...
                                        'rho', 1100,        ...
                                        'alpha_l', 57,    ...
                                        'alpha_s', 0,       ...
                                        'kt', 0.487,        ...
                                        'ct', 3.57e3,       ...
                                        'wt', 0 );
                                                                        
    parameters.muscle = struct(         'c_l', 1579,        ... % El-Brawany 2009
                                        'c_s', 0,           ...
                                        'rho', 1090,        ... % Duck 1990, pg 139
                                        'alpha_l', 3.2,     ... % Moros 1993 pg 586 (for a dog, but at least in vivo)
                                        'alpha_s', 0,       ...
                                        'kt', 0.68,         ... % Bhattacharya 2003 (in vivo means higher value)
                                        'ct', 3.0e3,        ... % Duck 1990, pg 28 (Ordinanz 1946 and Lehmann & Johnson 1958)
                                        'wt', 0 );          
                                
    parameters.muscle.wt = 0.027 * (parameters.muscle.rho * 1e-6 * 1e3 / 60);
    
    parameters.pigfat = struct(         'c_l', 1426,        ... % Duck 1990, pg 78
                                        'c_s', 0,           ...
                                        'rho', 916,         ... % Duck 1990, pg 138
                                        'alpha_l', 16.6,    ... % Duck 1990, pg 104
                                        'alpha_s', 0,       ...
                                        'kt', 0.16,         ...
                                        'ct', 2.64e+03,     ... % Duck 1990, pg 28 (average of Lehmann & Johnson 1958 and Robinson 1972)
                                        'wt', 4.25e-04 );
    
    parameters.water = struct(          'c_l', 1470,        ... % Water at 30C and small fatty layer
                                        'c_s', 0,           ... 
                                        'rho', 978,         ... % Combination of water with small fatty layer
                                        'alpha_l', 1,       ... % Assume small fatty layer
                                        'alpha_s', 0,       ... 
                                        'kt', 0.615,        ... 
                                        'ct', 4186,         ... 
                                        'wt', 0 );  
    
                                    
    parameters.marrow = struct(         'c_l', 1450,        ... 
                                        'c_s', 0,           ... 
                                        'rho', 1029,        ... 
                                        'alpha_l', 12.5,    ... 
                                        'alpha_s', 0,       ... 
                                        'kt', 0.28,         ... 
                                        'ct', 2.67e3,       ... 
                                        'wt', 0 );
                                    
    parameters.marrow.wt = 0.14 * (parameters.marrow.rho * 1e-6 * 1e3 / 60);
end